name: "CSPool"
port: 8080
version: "v0.0.1"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Tt112211"
  dbname: "CSPool"
  params:
    parseTime: "true"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
